version: "3.8"

services:
  tuity:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GIN_MODE=release
      - TIMELINE_DEFAULT_LIMIT=20
      - TIMELINE_MAX_LIMIT=100
      - RATE_LIMIT_TWEET_CREATE=10
      - RATE_LIMIT_FOLLOW_OPS=20
      - RATE_LIMIT_TIMELINE_REQUESTS=100
      - CACHE_TIMELINE_TTL=5m
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/health",
        ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s

  # Dev environment
  tuity-dev:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GIN_MODE=debug
      - TIMELINE_DEFAULT_LIMIT=10
      - TIMELINE_MAX_LIMIT=50
      - RATE_LIMIT_TWEET_CREATE=50
      - RATE_LIMIT_FOLLOW_OPS=100
      - RATE_LIMIT_TIMELINE_REQUESTS=500
      - CACHE_TIMELINE_TTL=1m
    volumes:
      - .:/app
    restart: unless-stopped
    profiles:
      - dev
